package cmd

import (
	"fmt"
	"io/ioutil"
	"os"
	"os/user"
	"strings"

	"github.com/spf13/cobra"
)

//Hush will use the existing configuration to remove the MOTD file and remove the line displaying it from the shell configuration
var Hush = &cobra.Command{
	Use:   "hush",
	Short: "Remove hush MOTD",
	Long:  `Remove the MOTD file originally generated by hush, but also update the users shell configuration to no longer attempt to display it`,
	Run: func(cmd *cobra.Command, args []string) {
		config, err := readConfig()

		if err != nil {
			cmd.PrintErr(err)
			return
		}

		//Remove the MOTD file
		user, err := user.Current()

		if err != nil {
			cmd.PrintErr(err)
			return
		}

		err = os.Remove(user.HomeDir + "/.motd")

		if err != nil {
			cmd.PrintErr(fmt.Errorf("Unable to delete the MOTD File: %s", err.Error()))
			return
		}

		//Open the config file for writing
		configfile, err := ioutil.ReadFile(user.HomeDir + "/" + config.ShellConfigurationFile)
		lines := strings.Split(string(configfile), "\n")
		needle := "cat " + user.HomeDir + "/.motd"

		for key, line := range lines {
			if strings.Contains(line, needle) {
				lines[key] = ""
			}
		}

		//Write the content back to the file
		updated := strings.Join(lines, "\n")
		ioutil.WriteFile(user.HomeDir+"/"+config.ShellConfigurationFile, []byte(updated), 0644)

	},
}

func init() {
	Clavis.AddCommand(Hush)
}
