# .gitHub/workflows/release.yml
name: Release Binaries

on:
  # Trigger on any new tag like v1.2.3
  push:
    tags:
      - 'v*'
  # Manual run if needed
  workflow_dispatch:

#env:
#  # Must match the binary name in your Makefile
#  BINARY_NAME: bs

jobs:
  build-and-release:
    name: Build & Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: '~> v2'
          args: release --clean